Repository TeraServ/octopus, pull requests merged in 2023-04, with the labels that each got.

#38 latest updates
  backend/teraHire/src/main/java/com/octopus/teraHire/model/Candidate.java
  backend/teraHire/src/main/java/com/octopus/teraHire/model/Job.java
  backend/teraHire/src/main/java/com/octopus/teraHire/repository/EventRepository.java
  backend/teraHire/src/main/java/com/octopus/teraHire/service/CandidateService.java
  backend/teraHire/src/main/java/com/octopus/teraHire/service/UserService.java
  frontend/terahire-ui/src/app/home/admin/user-list/user-list.component.html
  frontend/terahire-ui/src/app/home/dialog-delete/dialog-delete.component.ts
  frontend/terahire-ui/src/app/home/home.module.ts
  frontend/terahire-ui/src/app/home/recruitment/candidate-info/candidate-info.component.html
  frontend/terahire-ui/src/app/home/tasks/candidate/candidate.component.html
  frontend/terahire-ui/src/app/home/tasks/candidate/candidate.component.ts
  frontend/terahire-ui/src/app/home/tasks/job-edit/job-edit.component.html
  frontend/terahire-ui/src/app/home/tasks/job-list/job-list.component.html
  frontend/terahire-ui/src/app/home/tasks/job-list/job-list.component.ts
  frontend/terahire-ui/src/app/home/tasks/job-registration/job-registration.component.html
  frontend/terahire-ui/src/app/password-reset/password-reset.component.html
  frontend/terahire-ui/src/app/password-reset/password-reset.component.scss
  frontend/terahire-ui/src/app/password-reset/password-reset.component.ts
  frontend/terahire-ui/src/styles.scss
Labels: enhancement

#39 Documentation
  frontend/terahire-ui/src/app/home/tasks/candidate-list/candidate-list.component.ts
  frontend/terahire-ui/src/app/home/tasks/candidate-update/candidate-update.component.ts
  frontend/terahire-ui/src/app/home/tasks/job-edit/job-edit.component.ts
  frontend/terahire-ui/src/app/home/tasks/job-list/job-list.component.ts
  frontend/terahire-ui/src/app/home/tasks/job-registration/job-registration.component.ts
  frontend/terahire-ui/src/app/password-reset/password-reset.component.ts
Labels: documentation

#44 Job Expiry
  backend/teraHire/src/main/java/com/octopus/teraHire/service/JobService.java
  frontend/terahire-ui/src/app/home/dashboard/dashboard.component.ts
  frontend/terahire-ui/src/app/home/tasks/candidate-update/candidate-update.component.ts
  frontend/terahire-ui/src/app/home/tasks/job-edit/job-edit.component.html
  frontend/terahire-ui/src/app/home/tasks/job-registration/job-registration.component.html
  frontend/terahire-ui/src/app/home/tasks/tasks.component.ts
  frontend/terahire-ui/src/app/service/job.service.ts
Labels: enhancement

#45 Updation of Creation Date in Expired-to-Active Jobs Cases
  backend/teraHire/src/main/java/com/octopus/teraHire/service/JobService.java
  frontend/terahire-ui/src/app/home/tasks/candidate-update/candidate-update.component.ts
Labels: bug
